name: manage-azure-policy-b2af4dce
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service_service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**'
#      - 'policies/Modify_-_Configure_Azure_File_Sync_to_disable_public_network_access_0e07b2e9-6cd9-4c40-9ccb-52817b95133b/**'
#      - 'policies/Managed_identity_should_be_used_in_your_Function_App_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**'
#      - 'policies/Web_Application_Firewall_(WAF)_should_use_the_specified_mode_for_Application_Gateway_12430be1-6cc8-4527-a9a8-e3d38f250096/**'
#      - 'policies/Windows_machines_should_meet_requirements_for_Security_Options_-_Network_Security_1221c620-d201-468c-81e7-2817e6107e84/**'
#      - 'policies/Windows_machines_should_meet_requirements_for_Security_Options_-_System_settings_12017595-5a75-4bb1-9d97-4c2c939ea3c3/**'
#      - 'policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_1b8ca024-1d5c-4dec-8995-b1a932b41780/**'
#      - .github/workflows/manage-azure-policy-b2af4dce.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b2af4dce}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service_service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**
          policies/Modify_-_Configure_Azure_File_Sync_to_disable_public_network_access_0e07b2e9-6cd9-4c40-9ccb-52817b95133b/**
          policies/Managed_identity_should_be_used_in_your_Function_App_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**
          policies/Web_Application_Firewall_(WAF)_should_use_the_specified_mode_for_Application_Gateway_12430be1-6cc8-4527-a9a8-e3d38f250096/**
          policies/Windows_machines_should_meet_requirements_for_Security_Options_-_Network_Security_1221c620-d201-468c-81e7-2817e6107e84/**
          policies/Windows_machines_should_meet_requirements_for_Security_Options_-_System_settings_12017595-5a75-4bb1-9d97-4c2c939ea3c3/**
          policies/Public_network_access_on_Azure_SQL_Database_should_be_disabled_1b8ca024-1d5c-4dec-8995-b1a932b41780/**
